# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='registration',
            new_name='login',
        ),
    ]
