# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_project', '0002_auto_20180131_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='login',
            new_name='registration',
        ),
    ]
